### ISSUE TITLE
/lib folder required and not integrated into jar

### ISSUE THREAD

**Issue by mircea-vutcovici** [jewes/gchisto#2]
The /lib/ folder is required and it is not included in the build.

You need to manually copy it in the same folder as gchisto-1.0.1-SNAPSHOT.jar
The /lib folder contains: jcommon-1.0.12.jar  jfreechart-1.0.0.jar  junit-3.8.jar  swing-layout-1.0.2.jar

**Comment by jewes** [comment]
Thanks for the feedback.

The lib folder will be created and the the dependencies will be copied into the lib folder as part of the build/package process. They don't have to be created/copied manually. Just run the following command

```
mvn clean install
```

The gchisto-1.0.1-SNAPSHOT.tar.gz which includes everything will be created under the target folder. Let me know if you see something different.

**Comment by mircea-vutcovici** [comment]
Hi,

This is how I build the project - using `mvn clean install`. The problem in my case is that I wanted to build on one machine and use it on another. I think just adding in the documentation that the application requires to have those jars would help others in the same situation as me.

Thank you,
Mircea

**Comment by jewes** [comment]
Hi Mircea, 
You may want to copy target/gchisto-1.0.1-SNAPSHOT.tar.gz to the machine on which you want to use gchisto. Extract the tar.gz file and run `java -jar gchisto-1.0.1-SNAPSHOT.jar`.  Thanks!
